-- Comprehensive metadata completion for remaining 62 incomplete industry_taxonomy records
UPDATE industry_taxonomy 
SET 
  description = CASE 
    WHEN industry LIKE '%Semiconductor%' THEN 'Semiconductor and electronic component manufacturing'
    WHEN industry LIKE '%Tobacco%' THEN 'Tobacco product manufacturing and distribution'
    WHEN industry LIKE '%Uranium%' THEN 'Uranium mining and nuclear fuel processing'
    WHEN industry LIKE '%Coal%' THEN 'Coal mining and thermal power generation'
    WHEN industry LIKE '%Oil%' OR industry LIKE '%Gas%' THEN 'Oil and gas extraction and processing'
    WHEN industry LIKE '%Mining%' THEN 'Mineral extraction and processing operations'
    WHEN industry LIKE '%Steel%' OR industry LIKE '%Iron%' THEN 'Steel and iron manufacturing processes'
    WHEN industry LIKE '%Aluminum%' THEN 'Aluminum smelting and metal processing'
    WHEN industry LIKE '%Cement%' THEN 'Cement production and building materials'
    WHEN industry LIKE '%Chemical%' THEN 'Chemical manufacturing and processing'
    WHEN industry LIKE '%Pharmaceutical%' THEN 'Pharmaceutical research and drug manufacturing'
    WHEN industry LIKE '%Aviation%' OR industry LIKE '%Airline%' THEN 'Aviation services and aircraft operations'
    WHEN industry LIKE '%Shipping%' OR industry LIKE '%Maritime%' THEN 'Maritime transport and shipping services'
    WHEN industry LIKE '%Trucking%' OR industry LIKE '%Logistics%' THEN 'Ground transportation and logistics services'
    WHEN industry LIKE '%Electric%' OR industry LIKE '%Utility%' THEN 'Electric power generation and distribution'
    WHEN industry LIKE '%Agriculture%' OR industry LIKE '%Farming%' THEN 'Agricultural production and crop cultivation'
    WHEN industry LIKE '%Food%' OR industry LIKE '%Beverage%' THEN 'Food processing and beverage manufacturing'
    WHEN industry LIKE '%Textile%' OR industry LIKE '%Apparel%' THEN 'Textile manufacturing and apparel production'
    WHEN industry LIKE '%Paper%' OR industry LIKE '%Pulp%' THEN 'Paper and pulp manufacturing processes'
    WHEN industry LIKE '%Construction%' OR industry LIKE '%Building%' THEN 'Construction and building development services'
    WHEN industry LIKE '%Technology%' OR industry LIKE '%Software%' THEN 'Technology services and software development'
    WHEN industry LIKE '%Financial%' OR industry LIKE '%Banking%' THEN 'Financial services and banking operations'
    WHEN industry LIKE '%Retail%' OR industry LIKE '%Consumer%' THEN 'Retail and consumer goods distribution'
    WHEN industry LIKE '%Healthcare%' OR industry LIKE '%Medical%' THEN 'Healthcare services and medical equipment'
    WHEN industry LIKE '%Real Estate%' THEN 'Real estate development and property management'
    WHEN industry LIKE '%Media%' OR industry LIKE '%Entertainment%' THEN 'Media production and entertainment services'
    WHEN industry LIKE '%Waste%' THEN 'Waste management and recycling services'
    WHEN industry LIKE '%Water%' THEN 'Water treatment and distribution services'
    ELSE 'Specialized industry operations and services'
  END,
  ghg_protocol_alignment = CASE 
    WHEN industry LIKE '%Semiconductor%' THEN 'Scope 2 electricity-intensive manufacturing processes'
    WHEN industry LIKE '%Tobacco%' THEN 'Scope 3 agricultural supply chain emissions'
    WHEN industry LIKE '%Uranium%' OR industry LIKE '%Coal%' THEN 'Scope 1 direct extraction and processing emissions'
    WHEN industry LIKE '%Oil%' OR industry LIKE '%Gas%' THEN 'Scope 1 direct fossil fuel extraction emissions'
    WHEN industry LIKE '%Mining%' THEN 'Scope 1 direct extraction and heavy machinery emissions'
    WHEN industry LIKE '%Steel%' OR industry LIKE '%Iron%' OR industry LIKE '%Aluminum%' THEN 'Scope 1 high-temperature industrial processes'
    WHEN industry LIKE '%Cement%' THEN 'Scope 1 process emissions from limestone calcination'
    WHEN industry LIKE '%Chemical%' OR industry LIKE '%Pharmaceutical%' THEN 'Scope 1 chemical process and energy-intensive operations'
    WHEN industry LIKE '%Aviation%' OR industry LIKE '%Airline%' THEN 'Scope 1 direct combustion from jet fuel consumption'
    WHEN industry LIKE '%Shipping%' OR industry LIKE '%Maritime%' THEN 'Scope 1 marine fuel combustion emissions'
    WHEN industry LIKE '%Trucking%' OR industry LIKE '%Logistics%' THEN 'Scope 1 fleet vehicle fuel consumption'
    WHEN industry LIKE '%Electric%' OR industry LIKE '%Utility%' THEN 'Scope 1 power generation combustion emissions'
    WHEN industry LIKE '%Agriculture%' OR industry LIKE '%Farming%' THEN 'Scope 1 direct emissions from soil and fertilizer use'
    WHEN industry LIKE '%Food%' OR industry LIKE '%Beverage%' THEN 'Scope 3 agricultural supply chain intensive'
    WHEN industry LIKE '%Textile%' OR industry LIKE '%Apparel%' THEN 'Scope 3 global supply chain and manufacturing'
    WHEN industry LIKE '%Paper%' OR industry LIKE '%Pulp%' THEN 'Scope 1 energy-intensive pulping processes'
    WHEN industry LIKE '%Construction%' OR industry LIKE '%Building%' THEN 'Scope 3 materials and equipment supply chain'
    WHEN industry LIKE '%Technology%' OR industry LIKE '%Software%' THEN 'Scope 2 data center and office electricity consumption'
    WHEN industry LIKE '%Financial%' OR industry LIKE '%Banking%' THEN 'Scope 3 financed emissions from investment portfolio'
    WHEN industry LIKE '%Retail%' OR industry LIKE '%Consumer%' THEN 'Scope 3 product lifecycle and distribution'
    WHEN industry LIKE '%Healthcare%' OR industry LIKE '%Medical%' THEN 'Scope 2 facility energy and medical equipment'
    WHEN industry LIKE '%Real Estate%' THEN 'Scope 2 building energy consumption and operations'
    WHEN industry LIKE '%Media%' OR industry LIKE '%Entertainment%' THEN 'Scope 2 production facilities and broadcasting'
    WHEN industry LIKE '%Waste%' THEN 'Scope 1 waste processing and methane emissions'
    WHEN industry LIKE '%Water%' THEN 'Scope 2 energy-intensive treatment processes'
    ELSE 'Mixed scope emissions across operational activities'
  END,
  cdp_category = CASE 
    WHEN industry LIKE '%Semiconductor%' OR industry LIKE '%Technology%' THEN 'Technology Hardware & Equipment'
    WHEN industry LIKE '%Tobacco%' THEN 'Food, Beverage & Tobacco'
    WHEN industry LIKE '%Uranium%' OR industry LIKE '%Coal%' OR industry LIKE '%Oil%' OR industry LIKE '%Gas%' THEN 'Energy'
    WHEN industry LIKE '%Mining%' THEN 'Materials'
    WHEN industry LIKE '%Steel%' OR industry LIKE '%Iron%' OR industry LIKE '%Aluminum%' OR industry LIKE '%Cement%' THEN 'Materials'
    WHEN industry LIKE '%Chemical%' OR industry LIKE '%Pharmaceutical%' THEN 'Chemicals'
    WHEN industry LIKE '%Aviation%' OR industry LIKE '%Shipping%' OR industry LIKE '%Trucking%' THEN 'Transport Services'
    WHEN industry LIKE '%Electric%' OR industry LIKE '%Utility%' THEN 'Utilities'
    WHEN industry LIKE '%Agriculture%' OR industry LIKE '%Food%' OR industry LIKE '%Beverage%' THEN 'Food, Beverage & Tobacco'
    WHEN industry LIKE '%Textile%' OR industry LIKE '%Apparel%' THEN 'Textiles & Apparel'
    WHEN industry LIKE '%Paper%' OR industry LIKE '%Pulp%' THEN 'Paper & Forestry'
    WHEN industry LIKE '%Construction%' OR industry LIKE '%Building%' THEN 'Construction & Real Estate'
    WHEN industry LIKE '%Software%' THEN 'Technology Hardware & Equipment'
    WHEN industry LIKE '%Financial%' OR industry LIKE '%Banking%' THEN 'Financial Services'
    WHEN industry LIKE '%Retail%' OR industry LIKE '%Consumer%' THEN 'Retailing'
    WHEN industry LIKE '%Healthcare%' OR industry LIKE '%Medical%' THEN 'Healthcare'
    WHEN industry LIKE '%Real Estate%' THEN 'Construction & Real Estate'
    WHEN industry LIKE '%Media%' OR industry LIKE '%Entertainment%' THEN 'Media & Entertainment'
    WHEN industry LIKE '%Waste%' OR industry LIKE '%Water%' THEN 'Utilities'
    ELSE 'Industrials'
  END,
  sbti_pathway = CASE 
    WHEN industry LIKE '%Financial%' OR industry LIKE '%Banking%' THEN 'Portfolio-based targets'
    WHEN industry LIKE '%Steel%' OR industry LIKE '%Iron%' OR industry LIKE '%Aluminum%' OR industry LIKE '%Cement%' THEN 'Sectoral decarbonization approach'
    WHEN industry LIKE '%Electric%' OR industry LIKE '%Utility%' THEN 'Sectoral decarbonization approach'
    WHEN industry LIKE '%Aviation%' OR industry LIKE '%Shipping%' THEN 'Sectoral decarbonization approach'
    WHEN industry LIKE '%Technology%' OR industry LIKE '%Software%' THEN 'Already aligned with net-zero'
    ELSE 'Absolute emissions reduction'
  END,
  updated_at = now()
WHERE 
  description IS NULL 
  OR ghg_protocol_alignment IS NULL 
  OR cdp_category IS NULL 
  OR sbti_pathway IS NULL;